#!/usr/bin/zsh

# sinowealth-gaming-kb--keyboard wireless
# sino-wealth-gaming-keyboard-1 usb
LAYOUT=$(hyprctl devices -j | jq -r '.keyboards | map(select(.name == "sino-wealth-gaming-keyboard-1")).[0].active_keymap')
if [[ $LAYOUT = "null" ]]; then
  LAYOUT=$(hyprctl devices -j | jq -r '.keyboards | map(select(.name == "sinowealth-gaming-kb--keyboard")).[0].active_keymap')
fi

case $LAYOUT in
  "English (US)")
    echo "US";;
  "English (US, intl"*)
    echo "INTL";;
  *)
    echo "UNKNOWN";;
esac
