#!/usr/bin/zsh
hyprctl activewindow -j | jq -r .title
socat -u "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" - | stdbuf -o0 awk -F '>>|,' "/^activewindowv2>>/{system(\"hyprctl clients -j | jq -r 'map(select(.address == \\\"0x\" \$2 \"\\\")).[0].title'\")}"
